Repository eclipse-lemminx/lemminx, pull requests merged in 2020-05, with the labels that each got.

#647 Display test names in a more user-friendly way
  org.eclipse.lemminx/pom.xml
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/junit/CamelCaseDisplayNameGenerator.java
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/junit/CamelCaseDisplayNameGeneratorTest.java
  org.eclipse.lemminx/src/test/resources/junit-platform.properties
  pom.xml
Labels: build

#696 Fix cache result of external grammar info.
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DOMDocument.java
Labels: bug

#688 Validate XML with DTD/XML Schema by using xml-model
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DOMDocument.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/XMLSchemaErrorCode.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/diagnostics/LSPErrorReporterForXML.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/diagnostics/LSPXMLParserConfiguration.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/diagnostics/XMLValidator.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/AbstractLSPErrorReporter.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/LSPMessageFormatter.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelAwareParserConfiguration.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelConstants.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelDTDValidator.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelDeclaration.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelHandler.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelSchemaValidator.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xerces/xmlmodel/XMLModelValidator.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/xsd/participants/diagnostics/LSPErrorReporterForXSD.java
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/extensions/contentmodel/XMLModelDiagnosticsTest.java
  org.eclipse.lemminx/src/test/resources/xml-model/bound-to-dtd.xml
  org.eclipse.lemminx/src/test/resources/xml-model/bound-to-xsd-with-ns.xml
  org.eclipse.lemminx/src/test/resources/xml-model/bound-to-xsd.xml
Labels: validation

#718 Support advanced characters for entity name.
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/DTDErrorCode.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/entities/participants/EntitiesCompletionParticipant.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/entities/participants/EntitiesDefinitionParticipant.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/utils/StringUtils.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/utils/XMLPositionUtility.java
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/extensions/entities/EntitiesCompletionExtensionsTest.java
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/extensions/entities/EntitiesDefinitionExtensionsTest.java
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/utils/XMLPositionUtilityTest.java
Labels: DTD

#735 Fix collection of external entities depending on line ending
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DOMDocumentType.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/dtd/contentmodel/CMDTDContentModelProvider.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/dtd/contentmodel/CMDTDDocument.java
  org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/extensions/entities/EntitiesCompletionExtensionsTest.java
  org.eclipse.lemminx/src/test/resources/dtd/bug_vscode-xml_262.dtd
Labels: DTD, bug, completion
