Repository eclipse-lemminx/lemminx, pull requests merged in 2023-03, with the labels that each got.

#1198 Send (aggregated) server.document.open events at fixed periods.
  USAGE_DATA.md
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/telemetry/TelemetryCache.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/telemetry/TelemetryManager.java
Labels: enhancement, telemetry

#1504 Do not record number of file.identifier, file.extension instances.
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/telemetry/DocumentTelemetryInfo.java
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/telemetry/TelemetryCache.java
Labels: enhancement

#1507 XML language server should report select range capability in non dynamic mean
  org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/settings/capabilities/ServerCapabilitiesInitializer.java
Labels: bug
